In [30]:
#self explanotary, earlier we used the multinomialnb, now we gonna use the mlpclassifier in the neural network module

#libraries
from sklearn.neural_network import MLPClassifier
from sklearn.feature_extraction import text
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
import random as rd

def splitparagraphs(path, minsize=20):
    with open(path, "r", encoding="utf8") as file:
        splittedparas=[sentence for sentence in file.read().split("\n\n") if len(sentence)>minsize]
        return splittedparas


#preparing data
author = ['Virginia Woolf', 'Samuel Butler', 'Herman Melville', 'David Herbert Lawrence', 'Daniel Defoe', 'James Joyce']
filenames=["night_and_day_virginia_woolf.txt", "the_way_of_all_flash_butler.txt", "moby_dick_melville.txt", "sons_and_lovers_lawrence.txt", "robinson_crusoe_defoe.txt", "james_joyce_ulysses.txt"]
folder="Files/"
data=[];counter=0;label=[]
for file in filenames:
    path=folder+file
    paras=splitparagraphs(path, minsize=100)
    label+=[counter]*len(paras)
    data.extend(paras)
    counter+=1

#randomize
merged=list(zip(data, label))
merged=rd.sample(merged, len(merged))
data, label = (list(zip(*merged)))

#split train test
train_data, test_data, train_label, test_label = train_test_split(data, label, test_size=0.8, random_state=327364784)

#turning the data into a vector
vectorizer=text.CountVectorizer(stop_words=list(text.ENGLISH_STOP_WORDS))
train_data=vectorizer.fit_transform(train_data)
test_data=vectorizer.transform(test_data)

#neural network here
ANN=MLPClassifier(random_state=21763283, max_iter=300)
ANN.fit(train_data, train_label)
predicted=ANN.predict(test_data)
print(f'AccuracyScore: {accuracy_score(test_label, predicted)}')
print(f'f1Score      : {f1_score(test_label,predicted, average="macro")}')
print(confusion_matrix(test_label, predicted))

AccuracyScore: 0.8237919024814976
f1Score      : 0.8219321249722576
[[1285   28   14  155    4   40]
 [  62  858   23  100    4   62]
 [  45   24 1406   85    6   73]
 [  81   37   20 1643    6   68]
 [  27   37   22   51  422   31]
 [ 108   59   81  259    7 1955]]


In [1]:
from scipy import stats as st

#trynna predict something cuz why not?
path=folder+"moby_dick_melville.txt"            #try using that file cuz why not?
dumdata=splitparagraphs(path, minsize=75)
dumdata=rd.sample(dumdata, 5)

dumdata=vectorizer.transform(dumdata)

dumpredict=ANN.predict(dumdata)
print(author[st.mode(dumpredict, keepdims= False)[0]])
print(ANN.predict_proba(dumdata))

#checking accuracy
thecorrectlabelFR=[2]*dumdata.shape[0]
accuracy_score(thecorrectlabelFR, dumpredict)

NameError: name 'folder' is not defined