AUTHOR PREDICTION

Using:
1. Virginia Woolf: Night and Day
2. Samuel Butler: The Way of all Flesh
3. Herman Melville: Moby Dick
4. David Herbert Lawrence: Sons and Lovers
5. Daniel Defoe: The Life and Adventures of Robinson Crusoe
6. James Joyce: Ulysses

In [213]:
#At this point, you can just predict someone's writing bruh :skull:

#libraries needed
import os
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction import text
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import random as rd
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from scipy import stats as st
from sklearn.neural_network import MLPClassifier
def paragraphsplitter(path, minsize=20):
    '''
    Splitting your long ahh letter into several paragraphs.
    As tring less than minsize will be ignored, default-20
    '''
    with open(path, "r", encoding="utf8") as file:
        paragraphs=[sentence for sentence in file.read().split("\n\n") if len(sentence)>minsize]
    return paragraphs

if __name__ == "__main__": 
    #preparing data
    data=[]     #empty list for the data later
    label=[]    #empty list for the label
    counter=0
    author = ['Virginia Woolf', 'Samuel Butler', 'Herman Melville', 'David Herbert Lawrence', 'Daniel Defoe', 'James Joyce']
    filenames=["night_and_day_virginia_woolf.txt", "the_way_of_all_flash_butler.txt", "moby_dick_melville.txt", "sons_and_lovers_lawrence.txt", "robinson_crusoe_defoe.txt", "james_joyce_ulysses.txt"]
    folder="Files/"
    
        #we'll chop into paragraphs
    for file in filenames:
        path=folder+file
        paragraphs=paragraphsplitter(path, 100)
        data.extend(paragraphs)                             #merging to main data
        label+=[counter]*len(paragraphs)                    #making the appropriate labe;
        counter+=1

    #randomize sample(cuz this is required for train_test_split)[Though we'll be using the entire population LOL]
    merged = list(zip(data, label))
    randomerge=rd.sample(merged, len(merged))
    data,label = list(zip(*randomerge))
    
    #splitting data
    train_data, test_data, train_label, test_label= train_test_split(data, label, train_size=0.8, random_state=217632)
    
    #We gotta vectorize the data first JESSE!
    vectorizer=text.CountVectorizer(stop_words=list(text.ENGLISH_STOP_WORDS))
    train_data=vectorizer.fit_transform(train_data)
    test_data=vectorizer.transform(test_data)
    
    #Start classifying
        #Get Model and fit
    model=MultinomialNB(alpha=0.05)
    model.fit(train_data, train_label)        
    
        #test score
    predicted=model.predict(test_data)
    print(f'Accuracy:   {accuracy_score(test_label, predicted)}')
    print(f'F1_score:   {f1_score(test_label, predicted, average="macro")}')
    
    ANN=MLPClassifier(random_state=21763283, max_iter=300)
    ANN.fit(train_data, train_label)
    predicted=ANN.predict(test_data)
    print(f'AccuracyScore: {accuracy_score(test_label, predicted)}')
    print(f'f1Score      : {f1_score(test_label,predicted, average="macro")}')

Accuracy:   0.9042228994340444
F1_score:   0.8952204728114234
AccuracyScore: 0.8685241619503701
f1Score      : 0.8714071301566909


In [212]:
#trying to use the classifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
    #get a dummy data for predicting by using the way of all flash butler
path=folder+"the_way_of_all_flash_butler.txt"               #we gonna use that folder, authot[1]
dumparas=paragraphsplitter(path, minsize=200)

    #randomizing
dumparas=rd.sample(dumparas, 300)
vecotrdumbparas=vectorizer.transform(dumparas)                  
correctlabel=[1]*vecotrdumbparas.shape[0]                       #get the actual labels

    #begin predicting
predictdum=model.predict(vecotrdumbparas)

    #printing result of prediction
print(f'author: {author[st.mode(predictdum, keepdims=False)[0]]}')
print(accuracy_score(correctlabel, predictdum))
print(precision_score(correctlabel, predictdum, average="macro"))
print(confusion_matrix(correctlabel, predictdum))

author: Samuel Butler
0.9766666666666667
0.25
[[  0   0   0   0]
 [  1 293   1   5]
 [  0   0   0   0]
 [  0   0   0   0]]
